# Generated by Django 3.2 on 2021-04-29 20:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('first_authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=None)),
                ('secondary_authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None)),
                ('publication_year', models.CharField(blank=True, max_length=500, null=True)),
                ('notes_abstract', models.CharField(blank=True, max_length=1000, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=None)),
                ('alternate_title3', models.CharField(blank=True, max_length=500, null=True)),
                ('alternate_title2', models.CharField(blank=True, max_length=500, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('start_page', models.CharField(blank=True, max_length=50, null=True)),
                ('place_published', models.CharField(blank=True, max_length=500, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_attachments2', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('end_of_reference', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'db_table': 'table_article',
                'ordering': ['first_authors'],
            },
        ),
    ]
