# Generated by Django 3.2 on 2021-04-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.CharField(blank=True, max_length=50, null=True)),
                ('A2', models.CharField(blank=True, max_length=50, null=True)),
                ('TY', models.CharField(blank=True, max_length=50, null=True)),
                ('T1', models.CharField(blank=True, max_length=50, null=True)),
                ('Y1', models.IntegerField(blank=True, null=True)),
                ('N2', models.TextField(blank=True, max_length=250, null=True)),
                ('KW', models.CharField(blank=True, max_length=50, null=True)),
                ('JF', models.CharField(blank=True, max_length=50, null=True)),
                ('JA', models.CharField(blank=True, max_length=50, null=True)),
                ('VL', models.IntegerField(blank=True, null=True)),
                ('IS', models.IntegerField(blank=True, null=True)),
                ('SP', models.CharField(blank=True, max_length=50, null=True)),
                ('CY', models.CharField(blank=True, max_length=50, null=True)),
                ('PB', models.CharField(blank=True, max_length=50, null=True)),
                ('SN', models.CharField(blank=True, max_length=50, null=True)),
                ('M1', models.IntegerField(blank=True, null=True)),
                ('L2', models.CharField(blank=True, max_length=50, null=True)),
                ('UR', models.CharField(blank=True, max_length=50, null=True)),
                ('ER', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'db_table': 'table_article',
                'ordering': ['A1'],
            },
        ),
    ]
